// <auto-generated />
using System;
using ClaudeTools.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaudeTools.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209024013_AddSystemMetrics")]
    partial class AddSystemMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ClaudeTools.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputData")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptSent")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponse")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TokensIn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokensOut")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Operation");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ClaudeTools.Data.Entities.SystemMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("DiskUsedPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("MemTotalMb")
                        .HasColumnType("REAL");

                    b.Property<double>("MemUsedMb")
                        .HasColumnType("REAL");

                    b.Property<double>("NetRxBytesPerSec")
                        .HasColumnType("REAL");

                    b.Property<double>("NetTxBytesPerSec")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("SystemMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
